const $=s=>document.querySelector(s), app=$('#app'); let me=null, page=1, cache={};
const nav=[['dashboard','Overview'],['students','Students & Parents'],['academics','Classes & Subjects'],['attendance','Attendance'],['fees','Fees & Receipts'],['exams','Examinations & Results'],['staff','Staff & Teachers'],['settings','Settings'],['audit','Audit Log']];
const viewAccess={school_admin:['dashboard','students','academics','attendance','fees','exams','staff','settings','audit'],principal:['dashboard','students','academics','attendance','fees','exams','staff','audit'],teacher:['dashboard','students','attendance','exams'],accountant:['dashboard','students','fees']};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,method='GET',body){const r=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json()}catch{d={}}if(!r.ok)throw Error(d.error||'Something went wrong');return d}
function role(){return me.role.replace('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}
function shell(view){let allowed=viewAccess[me.role]||['dashboard'];app.innerHTML=`<div class="shell"><aside class="side"><div class="logo">SchoolFlow</div>${nav.filter(([id])=>allowed.includes(id)).map(([id,label])=>`<button class="nav ${id===view?'active':''}" onclick="show('${id}')">${label}</button>`).join('')}</aside><main class="main"><header class="top"><div><b>${esc(me.branch)}</b> · Academic year 2026–27</div><div class="profile"><div class="avatar">${me.name.split(' ').map(x=>x[0]).join('')}</div><span>${esc(me.name)}<br><small>${role()}</small></span><button class="secondary" onclick="logout()">Sign out</button></div></header><section class="content" id="content">Loading…</section></main></div>`}
function heading(title,sub,actions=''){return `<div class="toolbar"><div><h1>${title}</h1><p class="sub">${sub}</p></div><div class="actions">${actions}</div></div>`}
function card(label,value){return `<div class="card"><label>${label}</label><strong>${value}</strong></div>`}
function table(cols,items,fn){return `<div class="table-wrap"><table><thead><tr>${cols.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${items.length?items.map(fn).join(''):`<tr><td colspan="${cols.length}" class="empty">No records found.</td></tr>`}</tbody></table></div>`}
function modal(title,fields,submit){app.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modal-box"><div class="modal-title"><h2>${title}</h2><button class="close" onclick="closeModal()">×</button></div><form id="form" class="form-grid">${fields.map(f=>`<label class="${f.wide?'wide':''}"><span>${f.label}</span>${f.html||`<input name="${f.name}" type="${f.type||'text'}" ${f.required?'required':''} placeholder="${f.placeholder||''}">`}</label>`).join('')}<div class="wide actions"><button>Save</button><button type="button" class="secondary" onclick="closeModal()">Cancel</button></div></form></div></div>`);$('#form').onsubmit=async e=>{e.preventDefault();let b=Object.fromEntries(new FormData(e.target));try{await submit(b);closeModal();show(current)}catch(x){formError(x.message)}}}
function closeModal(){$('#modal')?.remove()} function formError(t){$('#form').insertAdjacentHTML('afterbegin',`<div class="notice wide">${esc(t)}</div>`)}
let current='dashboard';async function show(view){current=view;page=1;shell(view);try{await ({dashboard,students,academics,attendance,fees,exams,staff,settings,audit}[view])()}catch(e){$('#content').innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
async function dashboard(){let d=await api('/api/dashboard');let t=d.totals;$('#content').innerHTML=heading('Good morning, '+me.name.split(' ')[0],'Your school at a glance')+`<div class="cards">${card('Active students',t.students)}${card('Staff members',t.staff)}${card('Fee invoices',t.invoices)}${card('Outstanding fees','₹'+Number(t.due).toLocaleString('en-IN'))}</div><div class="panel"><h2>Recent fee invoices</h2><br>${table(['Student','Invoice','Amount','Status'],d.recent,x=>`<tr><td>${esc(x.student)}</td><td>${x.invoice_no}</td><td>₹${x.amount}</td><td><span class="pill ${x.status}">${x.status}</span></td></tr>`)}</div>`}
async function list(path,render){let d=await api(`${path}?page=${page}&q=${encodeURIComponent(cache.q||'')}`);render(d);}
function pager(d){return `<div class="pagination"><button class="secondary" ${d.page<=1?'disabled':''} onclick="page--;show(current)">Previous</button><span>Page ${d.page} of ${d.pages}</span><button class="secondary" ${d.page>=d.pages?'disabled':''} onclick="page++;show(current)">Next</button></div>`}
function searchBox(){return `<input style="max-width:260px" value="${esc(cache.q||'')}" placeholder="Search records" oninput="cache.q=this.value;page=1;show(current)">`}
async function students(){await list('/api/students',d=>{$('#content').innerHTML=heading('Students & parents','Admissions, guardian details and enrolment records',`<button class="secondary" onclick="window.location='/api/export/students'">Export CSV</button><button onclick="studentForm()">Add student</button><button onclick="parentForm()">Add parent</button>`)+`<div class="panel"><div class="toolbar"><h2>${d.total} students</h2>${searchBox()}</div>${table(['Admission','Student','Class','Parent','Phone','Status'],d.items,x=>`<tr><td>${x.admission_no}</td><td><b>${esc(x.first_name+' '+x.last_name)}</b><br><small>${x.gender||'—'}</small></td><td>${x.class_name} · ${x.section}</td><td>${esc(x.parent_name||'—')}</td><td>${x.phone||'—'}</td><td><span class="pill ${x.status}">${x.status}</span></td></tr>`)}${pager(d)}</div>`})}
async function studentForm(){let p=(await api('/api/parents')).items;modal('Add student',[{label:'Admission number',name:'admission_no',required:true,placeholder:'GF2026005'},{label:'First name',name:'first_name',required:true},{label:'Last name',name:'last_name'},{label:'Gender',name:'gender',html:'<select name="gender"><option>Female</option><option>Male</option><option>Other</option></select>'},{label:'Date of birth',name:'dob',type:'date'},{label:'Class',name:'class_name',required:true,placeholder:'Grade 5'},{label:'Section',name:'section',required:true,placeholder:'A'},{label:'Parent / guardian',name:'parent_id',html:`<select name="parent_id"><option value="">Select parent</option>${p.map(x=>`<option value="${x.id}">${esc(x.name)} · ${x.phone}</option>`).join('')}</select>`},{label:'Student phone',name:'phone'}],b=>api('/api/students','POST',b))}
function parentForm(){modal('Add parent / guardian',[{label:'Full name',name:'name',required:true},{label:'Phone',name:'phone',required:true},{label:'Email',name:'email',type:'email'},{label:'Relationship',name:'relation',html:'<select name="relation"><option>Father</option><option>Mother</option><option>Guardian</option></select>'}],b=>api('/api/parents','POST',b))}
async function academics(){let [d,c]=await Promise.all([api('/api/subjects'),api('/api/classes')]);$('#content').innerHTML=heading('Classes & subjects','Configure academic structure and subject allocation','<button onclick="classForm()">Add class / section</button><button class="secondary" onclick="subjectForm()">Add subject</button>')+`<div class="cards">${card('Configured subjects',d.total)}${card('Classes',new Set(c.items.map(x=>x.class_name)).size)}${card('Sections',c.total)}${card('Academic year','2026–27')}</div><div class="panel"><h2>Classes & sections</h2><br>${table(['Class','Section','Class teacher'],c.items,x=>`<tr><td>${x.class_name}</td><td>${x.section}</td><td>${esc(x.class_teacher||'Unassigned')}</td></tr>`)}</div><br><div class="panel"><div class="toolbar"><h2>Subject catalogue</h2>${searchBox()}</div>${table(['Subject','Code','Class'],d.items,x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.code}</td><td>${x.class_name}</td></tr>`)}${pager(d)}</div>`}
function classForm(){modal('Add class / section',[{label:'Class',name:'class_name',required:true,placeholder:'Grade 7'},{label:'Section',name:'section',required:true,placeholder:'A'},{label:'Class teacher',name:'class_teacher',placeholder:'Teacher name'}],b=>api('/api/classes','POST',b))}
function subjectForm(){modal('Add subject',[{label:'Subject name',name:'name',required:true},{label:'Subject code',name:'code',required:true,placeholder:'MAT-5'},{label:'Class',name:'class_name',required:true,placeholder:'Grade 5'}],b=>api('/api/subjects','POST',b))}
async function attendance(){let dt=cache.date||new Date().toISOString().slice(0,10),d=await api('/api/attendance?date='+dt);$('#content').innerHTML=heading('Daily attendance','Mark and review attendance by student',`<button onclick="saveAttendance()">Save attendance</button>`)+`<div class="panel"><div class="toolbar"><div><h2>${d.items.length} active students</h2></div><input style="max-width:190px" type="date" value="${dt}" onchange="cache.date=this.value;show('attendance')"></div>${table(['Student','Class','Status'],d.items,x=>`<tr class="attendance-row"><td><b>${esc(x.name)}</b><br><small>${x.admission_no}</small></td><td>${x.class_name} · ${x.section}</td><td><select data-student="${x.student_id}"><option ${x.status==='Present'?'selected':''}>Present</option><option ${x.status==='Absent'?'selected':''}>Absent</option><option ${x.status==='Late'?'selected':''}>Late</option></select></td></tr>`)}</div>`}
async function saveAttendance(){let records=[...document.querySelectorAll('[data-student]')].map(x=>({student_id:+x.dataset.student,status:x.value}));try{await api('/api/attendance','POST',{date:cache.date||new Date().toISOString().slice(0,10),records});alert('Attendance saved.');show('attendance')}catch(e){alert(e.message)}}
async function fees(){await list('/api/invoices',d=>{$('#content').innerHTML=heading('Fees & receipts','Issue invoices, collect payments and track balances',`<button onclick="invoiceForm()">New invoice</button><button class="secondary" onclick="receiptForm()">Record payment</button><button class="secondary" onclick="window.print()">Print</button>`)+`<div class="panel"><div class="toolbar"><h2>${d.total} invoices</h2>${searchBox()}</div>${table(['Invoice','Student','Fee type','Due date','Amount','Balance','Status'],d.items,x=>`<tr><td>${x.invoice_no}</td><td>${esc(x.student)}</td><td>${x.fee_type}</td><td>${x.due_date}</td><td>₹${x.amount}</td><td>₹${x.amount-x.paid_amount}</td><td><span class="pill ${x.status}">${x.status}</span></td></tr>`)}${pager(d)}</div>`})}
async function invoiceForm(){let s=(await api('/api/students')).items;modal('Create fee invoice',[{label:'Student',name:'student_id',required:true,html:`<select name="student_id">${s.map(x=>`<option value="${x.id}">${esc(x.first_name+' '+x.last_name)} · ${x.admission_no}</option>`).join('')}</select>`},{label:'Fee type',name:'fee_type',required:true,placeholder:'Term 1 Tuition'},{label:'Amount (₹)',name:'amount',type:'number',required:true},{label:'Due date',name:'due_date',type:'date',required:true}],b=>api('/api/invoices','POST',b))}
async function receiptForm(){let d=await api('/api/invoices');let inv=d.items.filter(x=>x.status!=='Paid');modal('Record payment',[{label:'Outstanding invoice',name:'invoice_id',required:true,html:`<select name="invoice_id">${inv.map(x=>`<option value="${x.id}">${x.invoice_no} · ${esc(x.student)} · ₹${x.amount-x.paid_amount}</option>`).join('')}</select>`},{label:'Amount received (₹)',name:'amount',type:'number',required:true},{label:'Payment mode',name:'payment_mode',html:'<select name="payment_mode"><option>Cash</option><option>UPI</option><option>Card</option><option>Bank Transfer</option></select>'}],b=>api('/api/receipts','POST',b))}
async function exams(){let d=await api('/api/exams');$('#content').innerHTML=heading('Examinations & results','Create assessments and securely enter subject marks',`<button onclick="examForm()">Create exam</button><button class="secondary" onclick="marksForm()">Enter marks</button>`)+`<div class="panel"><h2>Exams</h2><br>${table(['Exam','Term','Class','Starts on'],d.items,x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.term}</td><td>${x.class_name}</td><td>${x.starts_on}</td></tr>`)}</div>`}
function examForm(){modal('Create examination',[{label:'Exam name',name:'name',required:true},{label:'Term',name:'term',required:true,placeholder:'Term 1'},{label:'Class',name:'class_name',required:true,placeholder:'Grade 5'},{label:'Start date',name:'starts_on',type:'date',required:true}],b=>api('/api/exams','POST',b))}
async function marksForm(){let [e,s,sub]=await Promise.all([api('/api/exams'),api('/api/students'),api('/api/subjects')]);modal('Enter / update marks',[{label:'Exam',name:'exam_id',required:true,html:`<select name="exam_id">${e.items.map(x=>`<option value="${x.id}">${esc(x.name)} · ${x.class_name}</option>`).join('')}</select>`},{label:'Student',name:'student_id',required:true,html:`<select name="student_id">${s.items.map(x=>`<option value="${x.id}">${esc(x.first_name+' '+x.last_name)}</option>`).join('')}</select>`},{label:'Subject',name:'subject_id',required:true,html:`<select name="subject_id">${sub.items.map(x=>`<option value="${x.id}">${esc(x.name)} · ${x.class_name}</option>`).join('')}</select>`},{label:'Maximum marks',name:'max_marks',type:'number',required:true,placeholder:'100'},{label:'Marks obtained',name:'marks_obtained',type:'number',required:true},{label:'Remarks',name:'remarks',wide:true}],b=>api('/api/marks','POST',b))}
async function staff(){await list('/api/staff',d=>{$('#content').innerHTML=heading('Staff & teachers','Employee directory, designations and departments','<button onclick="staffForm()">Add staff member</button>')+`<div class="panel"><div class="toolbar"><h2>${d.total} staff members</h2>${searchBox()}</div>${table(['Employee no.','Name','Designation','Department','Contact','Status'],d.items,x=>`<tr><td>${x.employee_no}</td><td><b>${esc(x.name)}</b><br><small>${x.email||'—'}</small></td><td>${x.designation}</td><td>${x.department}</td><td>${x.phone||'—'}</td><td><span class="pill ${x.status}">${x.status}</span></td></tr>`)}${pager(d)}</div>`})}
function staffForm(){modal('Add staff member',[{label:'Employee number',name:'employee_no',required:true},{label:'Full name',name:'name',required:true},{label:'Designation',name:'designation',required:true},{label:'Department',name:'department'},{label:'Phone',name:'phone'},{label:'Email',name:'email',type:'email'},{label:'Joining date',name:'joining_date',type:'date'}],b=>api('/api/staff','POST',b))}
async function settings(){let d=await api('/api/settings');let x=d.item;$('#content').innerHTML=heading('School settings','School identity, contact details and academic-year setup')+`<div class="panel"><form class="form-grid" id="settings"><label><span>School name</span><input required name="name" value="${esc(x.name)}"></label><label><span>Academic year</span><input required name="academic_year" value="${esc(x.academic_year)}"></label><label class="wide"><span>Address</span><input name="address" value="${esc(x.address)}"></label><label><span>Phone</span><input name="phone" value="${esc(x.phone)}"></label><label><span>Email</span><input type="email" name="email" value="${esc(x.email)}"></label><div class="wide"><button>Save settings</button></div></form></div>`;$('#settings').onsubmit=async e=>{e.preventDefault();try{await api('/api/settings','POST',Object.fromEntries(new FormData(e.target)));alert('Settings saved.')}catch(x){alert(x.message)}}}
async function audit(){await list('/api/audit',d=>{$('#content').innerHTML=heading('Audit log','A tamper-evident activity trail for this branch')+`<div class="panel"><div class="toolbar"><h2>${d.total} events</h2>${searchBox()}</div>${table(['Time','User','Action','Entity','Details'],d.items,x=>`<tr><td>${x.occurred_at.replace('T',' ')}</td><td>${esc(x.user_name)}</td><td>${x.action}</td><td>${x.entity}</td><td>${esc(x.details)}</td></tr>`)}${pager(d)}</div>`})}
async function logout(){await api('/api/logout','POST');location.reload()}
async function start(){let d=await api('/api/me');if(!d.user){app.innerHTML=`<main class="login"><section class="login-card"><div class="logo">SchoolFlow ERP</div><p class="tag">A secure operating system for modern schools.</p><form id="login" class="form-grid"><label class="wide"><span>Email</span><input name="email" required type="email" value="admin@greenfield.edu.in"></label><label class="wide"><span>Password</span><input name="password" required type="password" value="Demo@123"></label><div class="wide"><button style="width:100%">Sign in</button></div><p class="sub wide">Demo accounts: admin, principal, teacher, accounts @greenfield.edu.in<br>Password: Demo@123</p></form></section></main>`;$('#login').onsubmit=async e=>{e.preventDefault();try{await api('/api/login','POST',Object.fromEntries(new FormData(e.target)));start()}catch(x){formError(x.message)}}}else{me=d.user;show('dashboard')}}start();
